# Generated by Django 3.1.3 on 2020-12-06 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=120)),
                ('list_price', models.FloatField()),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('order', models.IntegerField(default=1)),
                ('ratings', models.FloatField()),
                ('rating_count', models.IntegerField(default=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='backend.category')),
            ],
            options={
                'index_together': {('category', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField(null=True)),
                ('productName', models.CharField(max_length=200, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productDetail_product', to='backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ref_code', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('0', 'Processing'), ('1', 'Preparing'), ('2', 'Delivering'), ('3', 'Arriving'), ('4', 'Arrived')], default='0', max_length=2)),
                ('totalPrice', models.FloatField()),
                ('address', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(default='', max_length=200)),
                ('customer_name', models.CharField(default='', max_length=100)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='order_productDetails', to='backend.ProductDetail')),
            ],
        ),
    ]
